long_name = "Recaiden's Evolution Prodigies"
short_name = "rec-evolutions"
for_module = "tome"
version = {1,7,0}
addon_version = {1, 5, 1}
weight = 27801
author = { 'Recaiden' }
description = [[Dreadmaster not included]]
tags = {'prodigy', 'talent', 'evolution', 'recaiden', 'doomed', 'fallen', 'shadow','writhing one', 'gourmand', 'hollow', 'slow death', 'zephyr', 'archer'} -- tags MUST immediately follow description
hooks = true
overload = true
superload = true
data = true
